### ISSUE TITLE
Disabling the UNROUTED label?

### ISSUE THREAD

**Issue by TippyLion28** [AndreBL/ip6neigh#12]
Hey, I've installed your script and it does exactly what I needed it for. Awesome stuff. However, all of the IPv6 entries in the 'Connections' page of Luci show UNROUTED? Is it possible to disable this so that all the devices simply show only their IPv4 DHCP hostname? Thanks :)

**Comment by cvmiller** [comment]
You can disable this in the config file `/etc/config/ip6neigh`

Look for the UNROUTED section, and place '0' as the value. such as:
```
        # Default: 'UNROUTED'              
        #option unrouted_label  'UNROUTED'
        option unrouted_label   '0'                                              
```
And then restart ip6neigh
```
ip6neigh restart
```

**Comment by cvmiller** [comment]
Closing this, feel free to reopen it if needed.
