### ISSUE TITLE
oui install dont work

### ISSUE THREAD

**Issue by TrashCanMan** [AndreBL/ip6neigh#4]
```
root@OpenWrt:~# ip6neigh oui download
Downloading Nmap MAC prefixes...
Downloading 'http://linuxnet.ca/ieee/oui/nmap-mac-prefixes'
Connecting to 24.222.55.20:80
Failed to redirect to /ieee/oui/nmap-mac-prefixes on linuxnet.ca
```
PD: forgot to add some background, no idea if its needed, this is in an Archer C7 router with:
```
root@OpenWrt:~# uname -a
Linux OpenWrt 4.9.111 #0 Mon Jul 30 16:25:17 2018 mips GNU/Linux
```
On Luci:
`Powered by LuCI openwrt-18.06 branch (git-18.210.69179-6df9a57) / OpenWrt 18.06.0 r7188-b0b5c64c22`

More backgorund, the script installed correctly the ip6neigh part, its ""guessing"" names correctly, everything works correctly but i have a tv tunner that dont get a proper name and i was thinking that maybe the oui will solve that, for the moment ive set a static address with a name for it so im fine, but the oui script might need to be corrected...

Last bit of background, i can open manually the site on a browser without a problem, i see a list of codes/devices so i dont have routing problem as far as i can see...

**Comment by cvmiller** [comment]
The OUI will only give you a manufacturers Name, and the last 3 bytes of the MAC address (e.g. Apple345678). 

The problem is that Linuxnet has moved to a TLS webserver. You may try changing the line:
```
wget -O '/tmp/oui-raw.txt' 'http://linuxnet.ca/ieee/oui/nmap-mac-prefixes' || exit 2
```
to:
```
 wget --no-check-certificate -O '/tmp/oui-raw.txt' 'https://linuxnet.ca/ieee/oui/nmap-mac-prefixes' || exit 2
```
However SSL support is not built into Wget, and you will need to install ` libustream-ssl-*` libraries.

**Comment by TrashCanMan** [comment]
I just wanted to report the issue since i allredy solved this "issue" myself by setting a static ip and hostname manually, good to know for an alternative solution i guess for anyone else that wanders here in the future...in my case unless there is a new need for this im going to leave as it is for now...

**Comment by AndreBL** [comment]
I'm glad to see that most of the program still works, even after a long time without maintenance/updates. Functions that depend on external servers eventually break. When I have time I will try to update it according to Craig's solution.

**Comment by AndreBL** [comment]
Fixed. I replaced wget by curl and updated the url protocol to https. Curl is already in the list of required packages.
