### ISSUE TITLE
busybox ip command used from luci

### ISSUE THREAD

**Issue by billingd** [AndreBL/ip6neigh#5]
Thank you for ip6neigh.  It has been useful as I configure IPv6 on my home network.

I am running openwrt 17.01.4 on a NETGEAR WNDR3800.  I installed the "IPv6 Neighbors" and "ip6neigh log" custom commands in the luci gui as described in README.md.

The command "ip6neigh list active" works from the command line.  It didn't work initially from luci as ip6neigh used the busybox ip command from /sbin/ip, rather than the full ip from /usr/sbin/ip.  My work around was to add the full path to ip at line 160 of ip6neigh.

**Comment by AndreBL** [comment]
Hi.

Thanks for the feedback. I tried to investigate the issue in OpenWrt 18.06.1 x86:

The command 'which ip' gives me /sbin/ip, which is a symlink to /sbin/ip-full when the package ip-full is installed. If ip-full is not installed then the symlink points to /bin/busybox.

Could you assure you don't have more than a single ip package installed? Like ip-tiny and ip-full at the same time...
