### ISSUE TITLE
ip-full package URL 404

### ISSUE THREAD

**Issue by Callumpy** [AndreBL/ip6neigh#6]
Hi again Andre, 

Been using your tool for ages and need to do a reinstall, unfortunately it seems ip-full <4.4 has gone off of the packages list and the current version for OpenWRT/LEDE is still 4.16.

The link in the readme needs updating (if it's available anywhere else).

**Comment by Callumpy** [comment]
Ok, found it's still available for previous versions http://downloads.openwrt.org/releases/17.01.6/packages/

People looking under current/18.06.1 won't find anything over 4.19 it seems.

**Comment by cvmiller** [comment]
I have updated the Doc with your link. Thanks for that.
